### ISSUE TITLE
Kanboard plugin SubtaskDescription

### ISSUE THREAD

**Issue by alfredbuehler** [Shaun-Fong/Shaun-Fong#1]
Hi,
Unfortunately, you did not respond to any of my e-mails to you, so I am trying to contact you this way.

I have forked your archived repo SubtaskDescription, and want to continue the work you started there.
Now, the problem it, that you still occupy an entry in the directory's plugin.json file. This is useless, as the repo is archived, and you obviously do not want to develop it any longer.

I want to kindly ask you to free up the entry so that I can use it for the future work.

Cheers,
abu

**Comment by Shaun-Fong** [comment]
> Hi, Unfortunately, you did not respond to any of my e-mails to you, so I am trying to contact you this way.
> 
> I have forked your archived repo SubtaskDescription, and want to continue the work you started there. Now, the problem it, that you still occupy an entry in the directory's plugin.json file. This is useless, as the repo is archived, and you obviously do not want to develop it any longer.
> 
> I want to kindly ask you to free up the entry so that I can use it for the future work.
> 
> Cheers, abu

It looks like I didn't get your email, sorry about that. I have unarchived the repo, if you are willing to PR, welcome!

**Comment by alfredbuehler** [comment]
> It looks like I didn't get your email, sorry about that.

Very strange. I wrote to both e-mails that you're using in your commits. There is no other contact info available, and none of my mails were bounced.

> if you are willing to PR

No, as I'm not working on GitHub (mainly), PRs are not possible. I prefer to continue with my own repo, so I think I have to rename my repo/plugin.

Thanks for your prompt answer.

Cheers,
abu

**Comment by Shaun-Fong** [comment]
> > It looks like I didn't get your email, sorry about that.
> 
> Very strange. I wrote to both e-mails that you're using in your commits. There is no other contact info available, and none of my mails were bounced.
> 
> > if you are willing to PR
> 
> No, as I'm not working on GitHub (mainly), PRs are not possible. I prefer to continue with my own repo, so I think I have to rename my repo/plugin.
> 
> Thanks for your prompt answer.
> 
> Cheers, abu

Great. Gook luck!

**Comment by alfredbuehler** [comment]
Please take this into account:
By putting your repo to archive/readonly mode, users and devs had no chance to submit issues and/or PRs to you, and there is no known option to contact you. 
What else could be done, unless cloning the repo for fixing issues? For me, this was the only way to go. That's the way FOSS works.

**Comment by Shaun-Fong** [comment]
> Please take this into account: By putting your repo to archive/readonly mode, users and devs had no chance to submit issues and/or PRs to you, and there is no known option to contact you. What else could be done, unless cloning the repo for fixing issues? For me, this was the only way to go. That's the way FOSS works.

Thanks for the reminder. Actually, I just don't want to deal with this repo anymore ,and that's why I archive it. Unless someone asks like you. I'm glad the repo helps others, cheers.
